=== losgehts/BayesJunkEditor/samples/trainer_xml.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- The root element of this Mozilla training data XML file. -->
<!ELEMENT tokenfile (good_msgs, bad_msgs, token*)>

<!-- Represents the number of good (non-junk) messages processed by this token file. -->
<!ELEMENT good_msgs (#PCDATA)>

<!-- Represents the number of bad (junk) messages processed by this token file. -->
<!ELEMENT bad_msgs (#PCDATA)>

<!-- Represents a single token in the training file. -->
<!ELEMENT token (name, good, bad)>

<!-- Represents the string associated with this token. -->
<!ELEMENT name (#PCDATA)>

<!-- Represents the number of times this token has appeared in good (non-junk) emails. -->
<!ELEMENT good (#PCDATA)>

<!-- Represents the number of times this token has appeared in bad (junk) emails. -->
<!ELEMENT bad (#PCDATA)>

=== losgehts/BayesJunkEditor/samples/jangb.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE tokenfile SYSTEM "trainer_xml.dtd"><tokenfile>
	<good_msgs>38</good_msgs>
	<bad_msgs>320</bad_msgs>
	<token>
		<name>$</name>
		<good>4</good>
		<bad>18</bad>
	</token>
	<token>
		<name>$1</name>
		<good>3</good>
		<bad>7</bad>
	</token>
	<token>
		<name>$10</name>
		<good>1</good>
		<bad>8</bad>
	</token>
	<token>
		<name>$100</name>
		<good>0</good>
		<bad>8</bad>
	</token>
	<token>
		<name>$2</name>
		<good>0</good>
		<bad>7</bad>
	</token>
	<token>
		<name>$20</name>
		<good>2</good>
		<bad>19</bad>
	</token>
	<token>
		<name>$2000</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>$30</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>$38</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>$39</name>
		<good>0</good>
		<bad>12</bad>
	</token>
	<token>
		<name>$45</name>
		<good>0</good>
		<bad>16</bad>
	</token>
	<token>
		<name>$49</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>$5</name>
		<good>0</good>
		<bad>10</bad>
	</token>
	<token>
		<name>$50</name>
		<good>0</good>
		<bad>19</bad>
	</token>
	<token>
		<name>$500</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>$jangb</name>
		<good>28</good>
		<bad>2</bad>
	</token>
	<token>
		<name>'</name>
		<good>4</good>
		<bad>32</bad>
	</token>
	<token>
		<name>'color</name>
		<good>0</good>
		<bad>8</bad>
	</token>
	<token>
		<name>'font-family</name>
		<good>0</good>
		<bad>11</bad>
	</token>
	<token>
		<name>'font-size</name>
		<good>8</good>
		<bad>29</bad>
	</token>
	<token>
		<name>'http</name>
		<good>0</good>
		<bad>8</bad>
	</token>
	<token>
		<name>'inside</name>
		<good>0</good>
		<bad>8</bad>
	</token>
	<token>
		<name>'margin-bottom</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>'mso-margin-top-alt</name>
		<good>0</good>
		<bad>13</bad>
	</token>
	<token>
		<name>'unsub'</name>
		<good>0</good>
		<bad>12</bad>
	</token>
	<token>
		<name>--</name>
		<good>79</good>
		<bad>375</bad>
	</token>
	<token>
		<name>---</name>
		<good>1</good>
		<bad>5</bad>
	</token>
	<token>
		<name>----</name>
		<good>5</good>
		<bad>45</bad>
	</token>
	<token>
		<name>-----</name>
		<good>11</good>
		<bad>0</bad>
	</token>
	<token>
		<name>----------</name>
		<good>0</good>
		<bad>7</bad>
	</token>
	<token>
		<name>-------------------------------</name>
		<good>10</good>
		<bad>0</bad>
	</token>
	<token>
		<name>---------------------------------</name>
		<good>9</good>
		<bad>0</bad>
	</token>
	<token>
		<name>--------------------------------------------------</name>
		<good>18</good>
		<bad>5</bad>
	</token>
	<token>
		<name>---------------------------------------------------------------------------</name>
		<good>62</good>
		<bad>0</bad>
	</token>
	<token>
		<name>----------------------------------------------------------------------------</name>
		<good>0</good>
		<bad>8</bad>
	</token>
	<token>
		<name>--------------forwarded</name>
		<good>9</good>
		<bad>2</bad>
	</token>
	<token>
		<name>--butdx--</name>
		<good>0</good>
		<bad>75</bad>
	</token>
	<token>
		<name>--from</name>
		<good>9</good>
		<bad>2</bad>
	</token>
	<token>
		<name>--vlp--</name>
		<good>0</good>
		<bad>296</bad>
	</token>
	<token>
		<name>0000cc</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>0000ff</name>
		<good>9</good>
		<bad>157</bad>
	</token>
	<token>
		<name>00b000</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>00cc00</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>0cm</name>
		<good>5</good>
		<bad>0</bad>
	</token>
	<token>
		<name>0in</name>
		<good>0</good>
		<bad>14</bad>
	</token>
	<token>
		<name>0pt</name>
		<good>10</good>
		<bad>71</bad>
	</token>
	<token>
		<name>0pt'</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>0px</name>
		<good>1</good>
		<bad>97</bad>
	</token>
	<token>
		<name>1-212-504-3202</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>10pt</name>
		<good>1</good>
		<bad>13</bad>
	</token>
	<token>
		<name>10px</name>
		<good>2</good>
		<bad>45</bad>
	</token>
	<token>
		<name>11pt</name>
		<good>0</good>
		<bad>20</bad>
	</token>
	<token>
		<name>11px</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>12-cup</name>
		<good>0</good>
		<bad>7</bad>
	</token>
	<token>
		<name>12pt</name>
		<good>0</good>
		<bad>9</bad>
	</token>
	<token>
		<name>175452315-21052003</name>
		<good>9</good>
		<bad>0</bad>
	</token>
	<token>
		<name>190-610</name>
		<good>5</good>
		<bad>0</bad>
	</token>
	<token>
		<name>1pt</name>
		<good>0</good>
		<bad>20</bad>
	</token>
	<token>
		<name>1px</name>
		<good>0</good>
		<bad>18</bad>
	</token>
	<token>
		<name>2-lb</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>211-23-133-237</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>212-504-3202</name>
		<good>0</good>
		<bad>15</bad>
	</token>
	<token>
		<name>26-27</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>2d01</name>
		<good>0</good>
		<bad>8</bad>
	</token>
	<token>
		<name>2e</name>
		<good>3</good>
		<bad>80</bad>
	</token>
	<token>
		<name>2nd</name>
		<good>1</good>
		<bad>6</bad>
	</token>
	<token>
		<name>3333ff</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>3d</name>
		<good>9</good>
		<bad>14</bad>
	</token>
	<token>
		<name>3rd</name>
		<good>2</good>
		<bad>10</bad>
	</token>
	<token>
		<name>4d</name>
		<good>0</good>
		<bad>9</bad>
	</token>
	<token>
		<name>4f</name>
		<good>0</good>
		<bad>9</bad>
	</token>
	<token>
		<name>4pt</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>504netdeals</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>52f</name>
		<good>0</good>
		<bad>7</bad>
	</token>
	<token>
		<name>5in</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>5pt</name>
		<good>0</good>
		<bad>17</bad>
	</token>
	<token>
		<name>65d</name>
		<good>0</good>
		<bad>7</bad>
	</token>
	<token>
		<name>65t</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>6898d0</name>
		<good>0</good>
		<bad>8</bad>
	</token>
	<token>
		<name>6c</name>
		<good>0</good>
		<bad>7</bad>
	</token>
	<token>
		<name>6d</name>
		<good>0</good>
		<bad>20</bad>
	</token>
	<token>
		<name>6e</name>
		<good>0</good>
		<bad>14</bad>
	</token>
	<token>
		<name>6f</name>
		<good>6</good>
		<bad>82</bad>
	</token>
	<token>
		<name>6fr</name>
		<good>0</good>
		<bad>13</bad>
	</token>
	<token>
		<name>6fu</name>
		<good>3</good>
		<bad>31</bad>
	</token>
	<token>
		<name>6p2</name>
		<good>1</good>
		<bad>61</bad>
	</token>
	<token>
		<name>73tz</name>
		<good>0</good>
		<bad>7</bad>
	</token>
	<token>
		<name>75pt</name>
		<good>0</good>
		<bad>46</bad>
	</token>
	<token>
		<name>77w</name>
		<good>0</good>
		<bad>13</bad>
	</token>
	<token>
		<name>7a</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>7bit</name>
		<good>9</good>
		<bad>25</bad>
	</token>
	<token>
		<name>8bit</name>
		<good>5</good>
		<bad>34</bad>
	</token>
	<token>
		<name>8cup</name>
		<good>0</good>
		<bad>16</bad>
	</token>
	<token>
		<name>8e5f9c</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>8px</name>
		<good>0</good>
		<bad>12</bad>
	</token>
	<token>
		<name>a</name>
		<good>241</good>
		<bad>2499</bad>
	</token>
	<token>
		<name>a2</name>
		<good>0</good>
		<bad>7</bad>
	</token>
	<token>
		<name>a3zing29</name>
		<good>0</good>
		<bad>12</bad>
	</token>
	<token>
		<name>a4zing29</name>
		<good>0</good>
		<bad>11</bad>
	</token>
	<token>
		<name>aa</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>ab</name>
		<good>1</good>
		<bad>14</bad>
	</token>
	<token>
		<name>able</name>
		<good>8</good>
		<bad>28</bad>
	</token>
	<token>
		<name>about</name>
		<good>19</good>
		<bad>61</bad>
	</token>
	<token>
		<name>above</name>
		<good>10</good>
		<bad>11</bad>
	</token>
	<token>
		<name>absolute</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>absolutely</name>
		<good>0</good>
		<bad>16</bad>
	</token>
	<token>
		<name>abuse</name>
		<good>2</good>
		<bad>10</bad>
	</token>
	<token>
		<name>ac</name>
		<good>3</good>
		<bad>10</bad>
	</token>
	<token>
		<name>accept</name>
		<good>4</good>
		<bad>14</bad>
	</token>
	<token>
		<name>accepted</name>
		<good>0</good>
		<bad>11</bad>
	</token>
	<token>
		<name>access</name>
		<good>5</good>
		<bad>22</bad>
	</token>
	<token>
		<name>according</name>
		<good>2</good>
		<bad>7</bad>
	</token>
	<token>
		<name>account</name>
		<good>29</good>
		<bad>12</bad>
	</token>
	<token>
		<name>accountant</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>ace</name>
		<good>0</good>
		<bad>5</bad>
	</token>
	<token>
		<name>act</name>
		<good>4</good>
		<bad>25</bad>
	</token>
	<token>
		<name>action</name>
		<good>9</good>
		<bad>10</bad>
	</token>
	<token>
		<name>activate</name>
		<good>5</good>
		<bad>0</bad>
	</token>
	<token>
		<name>active</name>
		<good>2</good>
		<bad>7</bad>
	</token>
	<token>
		<name>activities</name>
		<good>2</good>
		<bad>6</bad>
	</token>
	<token>
		<name>actually</name>
		<good>2</good>
		<bad>21</bad>
	</token>
	<token>
		<name>ad</name>
		<good>5</good>
		<bad>18</bad>
	</token>
	<token>
		<name>add</name>
		<good>4</good>
		<bad>6</bad>
	</token>
	<token>
		<name>added</name>
		<good>5</good>
		<bad>18</bad>
	</token>
	<token>
		<name>addition</name>
		<good>6</good>
		<bad>3</bad>
	</token>
	<token>
		<name>additional</name>
		<good>3</good>
		<bad>8</bad>
	</token>
	<token>
		<name>address</name>
		<good>37</good>
		<bad>63</bad>
	</token>
	<token>
		<name>addressed</name>
		<good>0</good>
		<bad>6</bad>
	</token>
	<token>
		<name>addresser</name>
		<good>6</good>
		<bad>0</bad>
	</token>
	<token>
		<name>addresses</name>
		<good>2</good>
		<bad>34</bad>
	</token>
	<token>
		<name>adipex</name>
		<good>0</good>
		<bad>8</bad>
	</token>
	<token>
		<name>adresser</name>
